config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :supermarkets, only: [:index, :show]

  get 'cart/:code/increment', to: 'cart#increment'
  put 'cart/:code/decrement', to: 'cart#decrement'
  delete 'cart/:code/destroy', to: 'cart#destroy'
  delete 'cart/clear', to: 'cart#clear'

  namespace :validations, defaults: { format: :json } do
    get 'zipcodes', to: 'zipcodes#index'
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :supermarket
  belongs_to :unit

  # validations
  validates :supermarket, presence: true, associated: true
  validates :unit, presence: true, associated: true
  validates :slug, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
  validates :amount, presence: true, numericality: true
  validates :quantity, numericality: { only_integer: true }
end

app/models/supermarket.rb
class Supermarket < ActiveRecord::Base
  extend FriendlyId

  friendly_id :slug, use: [:slugged, :finders]

  # relationships
  has_and_belongs_to_many :zipcodes
  has_many :products

  # validations
  validates :slug, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  # validations
  validates :slug, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
  # relationships
  has_and_belongs_to_many :supermarkets

  # validations
  validates :cep, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  layout false

  def increment
    cart_increment(params[:code])
    set_products

    render :index
  end

  def decrement
    cart_decrement(params[:code])
    set_products

    render :index
  end

  def destroy
    session[:product_ids].delete(params[:code])
    set_products

    render :index
  end

  def clear
    session[:product_ids] = []
    set_products

    render :index
  end

  private

  def set_products
    @products = Product.where(slug: session[:product_ids]) if session[:product_ids]
  end

  def cart_decrement(code)
    products = session[:product_ids]
    equals = []

    products.each { |product| equals << product if product == code }
    products.delete(code)

    equals.pop
    session[:product_ids] = products + equals
  end

  def cart_increment(code)
    session[:product_ids] ||= []
    session[:product_ids] << code if code
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/supermarkets_controller.rb
class SupermarketsController < ApplicationController
  def index
    @zipcode = Zipcode.find_by_cep(params[:zipcode])
    @supermarkets = @zipcode.supermarkets if @zipcode
  end

  def show
    @cart_products = Product.where(slug: session[:product_ids]) if session[:product_ids]

    @supermarket = Supermarket.find(params[:id])
    @products = @supermarket.products if @supermarket
  end
end

app/controllers/validations/application_controller.rb
class Validations::ApplicationController < ApplicationController
end

app/controllers/validations/zipcodes_controller.rb
module Validations
  class ZipcodesController < ApplicationController
    def index
      zipcode = Zipcode.find_by_cep params[:zipcode]

      render json: zipcode.present? && zipcode.supermarkets.any?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
  def cart_total products
    total = 0
    products.decorate.each do |product|
      total = total + product.total(session)
    end
    number_to_currency total
  end
end

app/helpers/font_awesome_helper.rb
module FontAwesomeHelper
  def fa_icon icon, options = {}
    options[:class] = options[:class].present? ? "fa fa-fw fa-#{icon} #{options[:class]}" : "fa fa-fw fa-#{icon}"
    content_tag :i, nil, options
  end
end

app/views/cart/index.html.erb
<%= render 'shared/cart', products: @products %>

app/views/home/_form_modal.html.erb
<%= form_tag supermarkets_path, method: :get, id: 'form-search-by-zipcode' do %>
  <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <%= fa_icon :times, 'aria-hidden': true %>
          </button>
          <h3 class="modal-title"><%= t '.title' %></h3>
        </div>
        <div class="modal-body">
          <%= text_field_tag :zipcode, nil, class: 'form-control input-lg no-margin text-center', data: { mask: :cep } %>
        </div>
        <div class="modal-footer">
          <div class="col-sm-offset-1 col-sm-10">
            <button class="btn btn-block btn-lg btn-primary">
              <%= fa_icon :send %>
              <%= t '.button' %>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<h1 class="col-sm-offset-2 col-sm-8">
  <%= t '.slogan' %> <br />
  <small><%= t '.choose' %></small>
</h1>
<div class="col-sm-12 text-center">
  <button class="btn btn-lg btn-success" data-toggle="modal" data-target=".bs-example-modal-sm">
    <%= fa_icon :'shopping-cart' %> <%= t '.button.buy' %>
  </button>
</div>

<%= render 'form_modal' %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <title><%= ENV['APP_NAME'] %></title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <%= favicon_link_tag '/assets/favicon.ico' %>
</head>
<body>
<div id="loading">
  <div class="mask"></div>
  <div class="spiner">
    <%= fa_icon :refresh, class: :'fa-spin' %>
    <p><%= t '.loading' %></p>
  </div>
</div>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only"><%= ENV['APP_NAME'] %></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%= image_tag '/assets/logo-white.svg' %>
      <% end %>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 main">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/products/_product.html.erb
<div class="text-center thumbnail no-margin" style="margin-bottom:7px">
  <img src="<%= product.image_url %>" alt="<%= product.name %>" class="img-responsive" style="height:250px" />
  <h5>
    <div><%= product.name %></div>
    <small><%= product.amount_to_currency %> / <%= product.quantity_unit %></small>
  </h5>
</div>

app/views/shared/_cart.html.erb
<% if products.present? %>
  <% products.decorate.each do |product| %>
    <li class="list-group-item">
      <h5>
        <div data-product-code="<%= product.slug %>">
          <span class="destroy-to-cart text-danger pull-left">
            <%= fa_icon :times %>
          </span>

          <%= product.name %>

          <small><%= product.amount_to_currency %> / <%= product.quantity_unit %></small>

          <b><%= product.total_to_currency(session) %></b>

          <span class="add-to-cart btn btn-xs btn-success pull-right">
            <%= fa_icon :plus %>
          </span>

          <div class="pull-right text-center" style="padding-top:4px;width:35px;">
            <%= product.cart_quantity(session) %>
          </div>

          <span class="remove-to-cart btn btn-xs btn-danger pull-right">
            <%= fa_icon :minus %>
          </span>
        </div>
      </h5>
    </li>
  <% end %>
  <li class="list-group-item">
    <div class="text-right"><h3><%= cart_total(products) %></h3></div>
  </li>
<% else %>
  <li class="alert alert-info"><%= t '.not_found' %></li>
<% end %>

app/views/supermarkets/_modal.html.erb
<div id="product-<%= product.slug %>" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <%= fa_icon :times, 'aria-hidden': true %>
        </button>
        <h3 class="modal-title"><%= product.name %></h3>
      </div>
      <div class="modal-body">
        <%= render 'products/product', product: product %>
      </div>
    </div>
  </div>
</div>

app/views/supermarkets/index.html.erb
<h1 class="text-center"><%= t '.title', zipcode: params[:zipcode] %></h1>

<% if @supermarkets.present? %>

<div id="supermarkets" class="row">
  <% @supermarkets.each do |supermarket| %>
    <div class="col-md-4 col-xs-12 col-sm-6">
      <div class="form-group supermarket">
        <%= link_to supermarket do %>
          <img src="<%= supermarket.image_url %>" alt="<%= supermarket.name %>" class="img-responsive" />
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<% else %>
  <div class="alert alert-info"><h3 class="no-margin"><%= t '.not_found' %></h3></div>
<% end %>

app/views/supermarkets/show.html.erb
<h1 class="text-center"><%= t '.title', name: @supermarket.name %></h1>
<hr>

<% if @products.present? %>

<div id="products" class="row">
  <% @products.decorate.each do |product| %>
    <div class="col-md-4 col-xs-12 col-sm-6">
      <div class="form-group product text-center">
        <div class="row">
          <div class="col-md-12">
            <div data-toggle="modal" data-target="#product-<%= product.slug %>">
              <%= render 'products/product', product: product %>
            </div>

            <div class="row">
              <div class="col-md-12 text-center" data-product-code="<%= product.slug %>">
                <button id="remove-product-<%= product.slug %>" class="remove-to-cart btn btn-sm btn-danger bs-tooltip" title="<%= t '.button.remove' %>">
                  <%= fa_icon :minus %>
                </button>

                <button id="add-product-<%= product.slug %>" class="add-to-cart btn btn-sm btn-success bs-tooltip" title="<%= t '.button.add' %>">
                  <%= fa_icon :plus %>
                </button>
              </div>
            </div>

          </div>
        </div>
        <%= render 'modal', product: product %>
      </div>
    </div>
  <% end %>

  <h3><%= t '.cart.title' %></h3> <hr />

  <div class="row">
    <div class="col-md-12">
      <ul id="cart_products" class="list-group">
        <%= render 'shared/cart', products: @cart_products %>
      </ul>
    </div>
  </div>
</div>

<% else %>
  <div class="alert alert-info"><h3 class="no-margin"><%= t '.not_found' %></h3></div>
<% end %>